server:
  port: 8083

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: integration
      username: integration
      password: integration_123

  cloud:
    stream:
      bindings:
        output:
          destination: mns-trs-transport-out
          producer:
            required-groups: outConsumer
        input:
          destination: mns-trs-transport-in
          group: inConsumer


  rabbitmq:
    username: rabbitAdminUser
    password: rabbitAdminPwd
